// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hntybpzaesygqemgwpia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhudHlicHphZXN5Z3FlbWd3cGlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODc2NjksImV4cCI6MjA2Njg2MzY2OX0.YeCsdXmz63ms9axFU8YIvaOpMyRqpbfEFaSNL0LhK9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});